name: Lint The Website

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./site
      - name: Display structure of downloaded files
        run: ls -R ./site
      - name: Check HTML
        uses: chabad360/htmlproofer@master
        with:
          directory: ./site
